### ISSUE TITLE
Support for OpenCL

### ISSUE THREAD

**Issue by kpet** [SaschaWillems/gpuinfo.org#2]
First of all, thank you for all the work on the awesome tool that is gpuinfo.org :). I think OpenCL support would be an interesting addition. Have you considered it?

**Comment by ValZapod** [comment]
I suppose there are other apps for this. But yeah.

**Comment by SaschaWillems** [comment]
Yes, OpenCL surely would be a good addition.

**Comment by ValZapod** [comment]
Something like this, I suppose, http://www.ozone3d.net/gpudb/gpu.php?which=52519&v=2#opencl

The point here is that Nvidia just added 3.0 OpenCL but I am still confused what it does support and what not, like cl_khr_spir.

**Comment by SaschaWillems** [comment]
> Something like this, I suppose, http://www.ozone3d.net/gpudb/gpu.php?which=52519&v=2#opencl

If I add it to the database, it'll be a new standalone database and application. Just like with OpenGL, OpenGL ES and Vulkan.

>The point here is that Nvidia just added 3.0 OpenCL but I am still confused what it does support and what not, like cl_khr_spir.

OpenCL 3.0 is basically OpenCL 1.2 with all 2.0 features being optional.

**Comment by SaschaWillems** [comment]
See https://opencl.gpuinfo.org/ :)
