### ISSUE TITLE
Queue families, present reporting is broken for Linux section

### ISSUE THREAD

**Issue by Leopard1907** [SaschaWillems/gpuinfo.org#4]
https://vulkan.gpuinfo.org/listdevices.php?platform=linux

For any gpu, Supports Present bit shows as unsupported (X)

**Comment by SaschaWillems** [comment]
I'm aware of this. See https://github.com/SaschaWillems/VulkanCapsViewer/issues/120.

**Comment by Leopard1907** [comment]
Fixed with v `3.02 `, thanks.
