### ISSUE TITLE
Is it OK to re-publish reports downloaded from vulkan.gpuinfo.org?

### ISSUE THREAD

**Issue by kainino0x** [SaschaWillems/gpuinfo.org#6]
The WebGPU community group has often needed to make complex queries against the vulkan.gpuinfo.org database in order to determine baseline functionality for WebGPU. To facilitate this we ended up downloading the reports and querying them locally with a Python script (https://github.com/gpuweb/gpuweb/issues/1069#issuecomment-930710309)

Is it OK for us to have a public repository which re-publishes all of the downloaded JSON files under the Creative Commons Attribution 4.0 International License mentioned at the bottom of vulkan.gpuinfo.org? It would make it easier for members of the community group to use this data to make informed proposals and decisions.

**Comment by SaschaWillems** [comment]
Sure, I'm fine with that. Also if you need any help on getting data out of the database, feel free to contact me any time :)

**Comment by kainino0x** [comment]
Thank you very much! So far we've been just "scraping" reports from the site's API (which is nice and simple!) - although I didn't publish the scraping script with the data since I don't want to encourage a lot of people doing it :)

https://github.com/kainino0x/gpuinfo-vulkan-query
