### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by pkonecki** [SaschaWillems/gpuinfo.org#7]
I've found that, depending on the browser, webgl support is different than opengl es support (even though the features are almost the same).

It would be nice to have a version of gpuinfo.org that tracks WebGL reports, akin to https://webglreport.com/ but with the database goodness of gpuinfo.org.

Reports would be exclusively generated directly by the browser when visiting the website, eliminating the need to code a third party app. It would also be nice if it worked on mobile, the main reason being able to see which capabilities differ between desktop and mobile.

**Comment by SaschaWillems** [comment]
I don't have any plans for a WebGL database right now. While it's still widely used, WebGPU will probably replace it at some point and I don't have bandwidth for another database right now.
